server:
  port: 8000

spring:
  main:
    banner-mode: off
  application:
    name: ${name:poc-rabbitmq-stock-ms}
  profiles:
    active: ${profiles_active:local}
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: "neo"
    password: "trinity"

management:
  endpoint:
    health:
      show-details: "ALWAYS"
